{{- if and (eq "backend" .Values.appType) (and ( or (eq (toString .Values.istioEndUserAuth.enabled) "true") (eq (toString .Values.istioEndUserAuth.enabled) "True")) .Values.istioEndUserAuth.enabled) }}
# The evaluation is determined by the following rules:
#
# 1. If there are any DENY policies that match the request, deny the request.
# 2. If there are no ALLOW policies for the workload, allow the request.
# 3. If any of the ALLOW policies match the request, allow the request.
# 4. Deny the request.
#
# Ref: https://istio.io/latest/docs/reference/config/security/authorization-policy/
#
# --- Allow metrics policy ---
#
# Allow unauthenticated requests to the metrics endpoint. Note that there is a
# rule in the VirtualService config that will deny public requests to this
# metric endpoint.
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: "{{ template "app.name" . }}-allow-metrics-auth-policy"
  labels:
{{ include "default.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
  action: ALLOW
  rules:
  # Application metrics endpoint
  - to:
    - operation:
        paths:
          - "{{ .Values.metrics.path }}"
---
# --- Allow health check policy ---
#
# Allow unauthenticated calls to the istio-proxy healthcheck endpoint.
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: "{{ template "app.name" . }}-allow-health-auth-policy"
  labels:
{{ include "default.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
  action: ALLOW
  rules:
  # Istio-proxy readiness probe.
  - to:
    - operation:
        paths:
          - "/healthz/ready"
{{- if .Values.istioEndUserAuth.excludePaths }}
---
# --- Allow unauthenticated requests to custom paths ---
#
# This policy can be used to allow unauthenticated requests to any of the paths
# specified in the "excludePaths" list.
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: "{{ template "app.name" . }}-allow-auth-policy"
  labels:
{{ include "default.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
  action: ALLOW
  rules:
  - to:
    - operation:
        paths:
{{- range .Values.istioEndUserAuth.excludePaths }}
          - "{{ . }}"
{{- end }}
{{- end }}
{{- if .Values.istioEndUserAuth.includePaths }}
---
# --- Deny unauthenticated requests to custom paths ---
#
# This policy can be used to deny unauthenticated requests to any of the paths
# specified in the "excludePaths" list.
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: "{{ template "app.name" . }}-deny-auth-policy"
  labels:
{{ include "default.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
  action: DENY
  rules:
  - from:
    - source:
        notRequestPrincipals: ["*"]
    to:
    - operation:
        paths:
{{- range .Values.istioEndUserAuth.includePaths }}
          - "{{ . }}"
{{- end }}
{{- end }}
{{- end }}
