{{- if .Values.configs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.name" . }}-application-config
  labels:
{{ include "default.labels" . | indent 4 }}
data:
{{- range .Values.configs }}
  {{ .name }}: |
{{ .config | indent 4 }}
{{- end -}}
{{- end -}}
