{{- if eq (required ".Values.type entry required" .Values.type) "deployment"}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.name" . }}
  labels:
{{ include "default.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  {{- if .Values.deploymentStrategy }}
  strategy:
{{ toYaml .Values.deploymentStrategy | indent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "app.name" . }}
        release: {{ .Release.Name }}
      {{- if or (.Values.configs) (and ( or (eq (toString .Values.metrics.enabled) "true") (eq (toString .Values.metrics.enabled) "True")) .Values.metrics.enabled) (.Values.annotations) }}
      annotations:
      {{- if .Values.configs }}
        "checksum/application-config": "{{ include (print $.Template.BasePath "/configmap-application.yaml") . | sha256sum }}"
      {{- end }}
      {{- if .Values.backends }}
        "checksum/nginx-vhost-config": "{{ include (print $.Template.BasePath "/configmap-nginx-vhost.yaml") . | sha256sum }}"
      {{- end }}
      {{- if and ( or (eq (toString .Values.metrics.enabled) "true") (eq (toString .Values.metrics.enabled) "True")) .Values.metrics.enabled }}
{{ include "prometheus.labels" . | indent 8 }}
      {{- end }}
      {{- if .Values.annotations }}
      {{- with .Values.annotations }}
        {{- range $key, $value := . }}
        {{ $key }}: "{{ $value }}"
        {{- end }}
      {{- end }}
      {{- end }}
      {{- end }}
    spec:
      {{- if and ( or (eq (toString .Values.serviceAccount.create) "true") (eq (toString .Values.serviceAccount.create) "True")) .Values.serviceAccount.create }}
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      {{- end }}
      {{- if .Values.persistence.owner }}
      initContainers:
      - name: chowner
        image: busybox
        command:
          - chown
          - -R
          - {{ .Values.persistence.owner }}
          - {{ .Values.persistence.folder }}
        volumeMounts:
        - name: custom-data
          mountPath: {{ .Values.persistence.folder }}
        securityContext:
          seccompProfile:
            type: RuntimeDefault
      {{- end }}
      containers:
        {{- if .Values.sidecars }}
{{ toYaml .Values.sidecars | trim | indent 8 | replace "'" "" }}
        {{- end }}
        # If CloudSQL enabled is true/True AND useSqlProxy is true/True then create a cloudsql-proxy sidecar
       {{- if and ( or (eq (toString .Values.cloudsql.enabled) "true") (eq (toString .Values.cloudsql.enabled) "True")) .Values.cloudsql.enabled }}
       {{- if and ( or (eq (toString .Values.cloudsql.useSqlProxy) "true") (eq (toString .Values.cloudsql.useSqlProxy) "True")) .Values.cloudsql.useSqlProxy }}
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:{{ .Values.cloudsql.version }}
          command:
          - /cloud_sql_proxy
          args:
          - -instances={{ required "A valid .Values.cloudsql.instance entry required!" .Values.cloudsql.instance }}=tcp:5432
          securityContext:
{{ include "global.ContainerSecurityContext" . | indent 12 }}
        {{- end }}
        {{- end }}
        {{- if and (and ( or (eq (toString .Values.oauth2Proxy.enabled) "true") (eq (toString .Values.oauth2Proxy.enabled) "True")) .Values.oauth2Proxy.enabled) (eq .Values.appType "frontend") }}
        - name: oauth2-proxy
          image: {{ .Values.oauth2Proxy.image }}:{{ .Values.oauth2Proxy.version }}
          imagePullPolicy: Always
          ports:
          - name: http-oauth2
            containerPort: {{ .Values.oauth2Proxy.port }}
          args:
          - --config=/configmaps/oauth2-proxy-client-config.yaml
          env:
          - name: OAUTH2_PROXY_UPSTREAMS
            value: "https://127.0.0.1:{{ default .Values.port.containerport .Values.apiGateway.port }}"
          - name: OAUTH2_PROXY_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: {{ template "app.name" . }}-oauth2-proxy
                key: client-id
          - name: OAUTH2_PROXY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ template "app.name" . }}-oauth2-proxy
                key: client-secret
          - name: OAUTH2_PROXY_COOKIE_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ template "app.name" . }}-oauth2-proxy
                key: cookie-secret
          volumeMounts:
          - name: oauth2-proxy-client-config
            mountPath: "/configmaps/"
            readOnly: true
          securityContext:
{{ include "global.ContainerSecurityContext" . | indent 12 }}
        {{- end }}
        {{- if .Values.backends }}
        - name: nginx-gateway
          image: {{ .Values.apiGateway.image }}:{{ .Values.apiGateway.version }}
          imagePullPolicy: Always
          ports:
          - name: http-nginx
            containerPort: {{ .Values.apiGateway.port }}
          volumeMounts:
          - name: nginx-vhost-config-volume
            mountPath: "/opt/bitnami/nginx/conf/server_blocks"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
        {{- end }}
        - name: {{ template "app.name" . }}-cont
          image: {{ template "app.imageRepository" . }}:{{ template "app.imageTag" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.image.command }}
          command:
          {{-  range .Values.image.command }}
            - {{ . }}{{ end }}
          {{- end }}
          {{- if .Values.image.args }}
          args:
          {{-  range .Values.image.args }}
            - {{ . }}{{ end }}
          {{- end }}
          {{- if or (.Values.configs) (.Values.volumeMounts) (and ( or (eq (toString .Values.persistence.enabled) "true") (eq (toString .Values.persistence.enabled) "True")) .Values.persistence.enabled) }}
          volumeMounts:
          {{- if .Values.volumeMounts }}
{{ toYaml .Values.volumeMounts | trim | indent 10 }}
          {{- end }}
          {{- if .Values.configs }}
          {{- range .Values.configs }}
          - name: application-config-volume
            mountPath: {{ .mountPath }}/{{ .name }}
            subPath: {{ .name }}
            readOnly: true
          {{- end }}
          {{- end }}
          {{- if and ( or (eq (toString .Values.persistence.enabled) "true") (eq (toString .Values.persistence.enabled) "True")) .Values.persistence.enabled }}
          - name: custom-data
            mountPath: {{ .Values.persistence.folder }}
          {{- end }}
          {{- end }}
          ports:
          - name: {{ .Values.port.name | trunc 15 | trimSuffix "-" }}
            containerPort: {{ .Values.port.containerport }}
          {{- if .Values.extraPorts }}
          {{- range .Values.extraPorts }}
          {{- if .containerport }}
          - name: {{ .name | trunc 15 | trimSuffix "-" }}
            containerPort: {{ .containerport }}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- if and ( or (eq (toString .Values.probes.liveness.enabled) "true") (eq (toString .Values.probes.liveness.enabled) "True")) .Values.probes.liveness.enabled }}
          livenessProbe:
{{ toYaml .Values.probes.liveness.livenessProbe | indent 12 }}
          {{- end }}
          {{- if and ( or (eq (toString .Values.probes.readiness.enabled) "true") (eq (toString .Values.probes.readiness.enabled) "True")) .Values.probes.readiness.enabled }}
          readinessProbe:
{{ toYaml .Values.probes.readiness.readinessProbe | indent 12 }}
          {{- end }}
          {{- if and ( or (eq (toString .Values.resources.enabled) "true") (eq (toString .Values.resources.enabled) "True")) .Values.resources.enabled }}
          resources:
            limits:
{{ toYaml .Values.resources.limits | trim | indent 14 }}
            requests:
{{ toYaml .Values.resources.requests | trim | indent 14 }}
          {{- end }}
          {{- if .Values.environmentVariables }}
          env:
          {{- with .Values.environmentVariables }}
{{ toYaml . | trim | indent 12 }}
          {{- end }}
          {{- end }}
          securityContext:
            allowPrivilegeEscalation: {{ .Values.ContainerSecurityContext.allowPrivilegeEscalation }}
            privileged: {{ .Values.ContainerSecurityContext.privileged }}
            readOnlyRootFilesystem: {{ .Values.ContainerSecurityContext.readOnlyRootFilesystem }}
            runAsNonRoot: {{ .Values.ContainerSecurityContext.runAsNonRoot }}
            runAsUser: {{ .Values.ContainerSecurityContext.runAsUser }}
            runAsGroup: {{ .Values.ContainerSecurityContext.runAsGroup }}
            {{- if .Values.ContainerSecurityContext.capabilities }}
            capabilities:
              {{- if .Values.ContainerSecurityContext.capabilities.add }}
              add: {{ .Values.ContainerSecurityContext.capabilities.add }}
              {{- end }}
              {{- if .Values.ContainerSecurityContext.capabilities.drop }}
              drop: {{ .Values.ContainerSecurityContext.capabilities.drop }}
              {{- end }}
            {{- end }}
            {{- if .Values.ContainerSecurityContext.seccompProfile }}
            seccompProfile:
              type: {{ .Values.ContainerSecurityContext.seccompProfile.type }}
            {{- end }}
          {{- if .Values.lifecycle }}
          {{- if .Values.lifecycle.postStartCommand }}
          lifecycle:
            postStart:
              exec:
                command:
{{ toYaml .Values.lifecycle.postStartCommand | trim | indent 16}}
          {{- end }}
          {{- end }}
      {{- if .Values.hostAliases }}
      hostAliases:
{{ toYaml .Values.hostAliases | trim | indent 8 }}
      {{- end }}
{{- if or (.Values.volumes) (.Values.configs) (and ( or (eq (toString .Values.persistence.enabled) "true") (eq (toString .Values.persistence.enabled) "True")) .Values.persistence.enabled) (.Values.backends) (and (and ( or (eq (toString .Values.oauth2Proxy.enabled) "true") (eq (toString .Values.oauth2Proxy.enabled) "True")) .Values.oauth2Proxy.enabled) (eq .Values.appType "frontend")) }}
      volumes:
{{- if .Values.volumes }}
{{ toYaml .Values.volumes | trim | indent 8 }}
{{- end }}
{{- if and (and ( or (eq (toString .Values.oauth2Proxy.enabled) "true") (eq (toString .Values.oauth2Proxy.enabled) "True")) .Values.oauth2Proxy.enabled) (eq .Values.appType "frontend") }}
        - name: "oauth2-proxy-client-config"
          configMap:
            name: "{{ template "app.name" . }}-oauth2-proxy-client-config"
{{- end }}
{{- if .Values.configs }}
        - name: application-config-volume
          configMap:
            name: "{{ template "app.name" . }}-application-config"
{{- end }}
{{- if and ( or (eq (toString .Values.persistence.enabled) "true") (eq (toString .Values.persistence.enabled) "True")) .Values.persistence.enabled }}
        - name: custom-data
          persistentVolumeClaim:
            claimName: {{ template "app.name" . }}-pvc
{{- end }}
{{- if .Values.backends }}
        - name: nginx-vhost-config-volume
          configMap:
            name: "{{ template "app.name" . }}-nginx-vhost-config"
{{- end }}
{{- end }}
      securityContext:
{{- if .Values.PodSecurityContext.runAsNonRoot }}
        runAsNonRoot: {{ .Values.PodSecurityContext.runAsNonRoot }}
{{- end }}
{{- if .Values.PodSecurityContext.runAsUser }}
        runAsUser: {{ .Values.PodSecurityContext.runAsUser }}
{{- end }}
{{- if .Values.PodSecurityContext.runAsGroup }}
        runAsGroup: {{ .Values.PodSecurityContext.runAsGroup }}
{{- end }}
{{- if .Values.PodSecurityContext.fsGroup }}
        fsGroup: {{ .Values.PodSecurityContext.fsGroup }}
{{- end }}
{{- if .Values.ContainerSecurityContext.seccompProfile }}
        seccompProfile:
          type: {{ .Values.ContainerSecurityContext.seccompProfile.type }}
{{- end }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}

{{- end}}
