{{- if and (and ( or (eq (toString .Values.persistence.enabled) "true") (eq (toString .Values.persistence.enabled) "True")) .Values.persistence.enabled) (and ( or (eq (toString .Values.persistence.createPvc) "true") (eq (toString .Values.persistence.createPvc) "True")) .Values.persistence.createPvc) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "app.name" . }}-pvc
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
