{{- if .Values.egress }}
{{- range .Values.egress }}
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: "{{ $.Values.name }}-{{ . | replace "*" "wildcard" }}"
  labels:
{{ include "default.labels" $ | indent 4 }}
spec:
  hosts:
  - "{{ . }}"
  exportTo:
  - "."
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
{{- end }}
{{- end }}
