# ServiceAccount options
# on .Values.serviceAccount.create=true, started pod is automatically assigned defined service account
# Service account cannot be added/changed to a running pod
{{- if and ( or (eq (toString .Values.serviceAccount.create) "true") (eq (toString .Values.serviceAccount.create) "True")) .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app.serviceAccountName" . }}
  labels:
{{ include "default.labels" . | indent 4 }}
{{- if .Values.serviceAccount.annotations }}
{{- with .Values.serviceAccount.annotations }}
  annotations:
  {{- range $key, $value := . }}
    {{ $key }}: {{ $value }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
