{{- if ((((.Values.access).ingress).external).gateways) }}
{{/*TODO: Make pretty...*/}}
{{ $shouldRender := false }}
{{- range .Values.access.ingress.external.gateways }}
{{- if (eq (toString .type) "public") }}
{{- $shouldRender = true}}
{{- end }}
{{- end }}

{{- if $shouldRender }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "app.name" . }}
  labels:
{{ include "default.labels" . | indent 4 }}
spec:
  hosts:
{{- $appName := include "app.name" . -}}
{{- $domainName := .Values.domain -}}
{{- if .Values.subdomains }}
{{- if not .Values.urlhosts }}
{{- range .Values.subdomains }}
  - {{ $appName }}.{{ . }}.{{ $domainName }}
{{- end }}
{{- end }}
{{- end }}
{{- if .Values.urlhosts }}
{{- if not .Values.subdomains }}
{{- range .Values.urlhosts }}
  - {{ . }}.{{ $domainName }}
{{- end }}
{{- end }}
{{- end }}
{{- if and .Values.urlhosts .Values.subdomains }}
{{ $urlhosts := .Values.urlhosts }}
{{- range $subdomain := .Values.subdomains }}
{{- range $urlhosts }}
  - {{ . }}.{{ $subdomain }}.{{ $domainName }}
{{- end }}
{{- end }}
{{- end }}
  - {{ template "app.name" . }}.{{ template "app.cluster" . }}.{{ .Values.domain }}
  gateways:
  - istio-system/{{ template "app.cluster" . }}-gateway
  http:
{{- if .Values.routes }}
{{- $appName := include "app.name" . }}
{{- $releaseNamespace := .Release.Namespace }}
{{- range .Values.routes }}
  - match:
    - uri:
        {{ .type }}: "{{ .name }}"
    route:
    - destination:
        host: {{ $appName }}.{{ $releaseNamespace }}.svc.cluster.local
        port:
          number: {{ .serviceport }}
{{- end }}
{{- end }}
{{- if and ( or (eq (toString .Values.metrics.enabled) "true") (eq (toString .Values.metrics.enabled) "True")) .Values.metrics.enabled }}
  - match:
    - uri:
{{- if .Values.metrics.path }}
        prefix: "{{ .Values.metrics.path }}"
{{- else }}
        prefix: "/metrics"
{{- end }}
    rewrite:
      uri: "/"
    route:
    - destination:
        host: {{ template "app.name" . }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: {{ .Values.port.serviceport }}
{{- end }}
  - route:
    - destination:
        host: {{ template "app.name" . }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: {{ .Values.port.serviceport }}
{{- end }}
{{- end }}
