apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: {{ include "flux-alerts.fullname" . }}
  labels:
    {{- include "flux-alerts.labels" . | nindent 4 }}
spec:
  address: https://slack.com/api/chat.postMessage
  channel: {{ .Values.slack.channel }}
  secretRef:
    name: {{ include "flux-alerts.fullname" . }}
  type: slack
