{{- if ((.Values.slack).token) }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ include "flux-alerts.fullname" . }}
  labels:
    {{- include "flux-alerts.labels" . | nindent 4 }}
spec:
  encryptedData:
    token: {{ .Values.slack.token }}
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: {{ include "flux-alerts.fullname" . }}
{{- end }}
